#!/bin/sh
#source https://github.com/x70b1/polybar-scripts

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi

# if ! updates_aur=$(cower -u 2> /dev/null | wc -l); then
echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
if [ $? -eq 0 ]; then
    if ! updates_aur=$(yay -Qum | wc -l); then
        updates_aur=0
    fi
fi


echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
if [ $? -eq 0 ]; then
    updates=$(("$updates_arch" + "$updates_aur"))
else
    #If no internet, assume no updates
    updates=0
    exit
fi


if [ "$updates" -gt 0 ]; then
    echo "$updates" > /tmp/updates.txt
else
    echo "0" > /tmp/updates.txt
fi
