#!/bin/bash

## Created By Aditya Shakya

MENU="$(echo -e " Lock\n Logout\n Reboot\n Shutdown" | dmenuopts)"
            case "$MENU" in
                *Lock) slock ;;
                *Logout) killall dwm ;;
                *Reboot) sudo reboot ;;
                *Shutdown) sudo shutdown now ;;
esac
