#!/bin/bash

## Created By Aditya Shakya

MENU="$(echo -e " Lock\n Logout\n Reboot\n Shutdown" | dmenuopts)"
            case "$MENU" in
                *Lock) slock ;;
                *Logout) rm /tmp/Xorg.lock ; killall dwm ;;
                *Reboot) rm /tmp/Xorg.lock ; sudo reboot ;;
                *Shutdown) rm /tmp/Xorg.lock ; sudo shutdown now ;;
esac
