#!/bin/sh

# Source Colors
. "$XDG_CACHE_HOME/wal/colors.sh"

# Colors
bspc config normal_border_color "$foreground"
bspc config active_border_color "$color4"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$foreground"


bspc monitor DP-2 -d 1 3 5 7 9
bspc monitor DP-5 -d 2 4 6 8 10 Spotify


bspc config border_width              2
bspc config window_gap                8

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config paddingless_monocle       true

bspc config focus_follows_pointer     true
bspc config pointer_follows_monitor   true

bspc config single_monocle            true

bspc config bottom_padding            23


bspc rule -a discord desktop=4 follow=off focus=off
bspc rule -a Thunderbird desktop=4 follow=off focus=off
bspc rule -a startupterm1 desktop=5 follow=off focus=off
bspc rule -a startupterm2 desktop=6 follow=off focus=off
bspc rule -a Steam desktop=3 follow=off focus=off
bspc rule -a lutris desktop=3 follow=off focus=off
bspc rule -a spotify desktop=Spotify follow=off focus=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Google-chrome:configure.ergodox-ez.com state=floating sticky=on

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Fix java applications behaving weirdly due to bspwm
wmname LG3D

# Autostart
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
	touch /tmp/bspwm-startup.lock
	# Set social to monocle layout
	bspc desktop 4 -l next
	sxhkd &
	feh --bg-fill --no-fehbg $HOME/Pictures/Wallpapers/wallpaper.png &
	xautolock -time 15 -locker "/home/aiden/.scripts/screenoff.sh" &
	protonmail-bridge --noninteractive &
	nextcloud --background &
    redshift &
	$XDG_CONFIG_HOME/polybar/launch.sh &
	$HOME/.scripts/bspwmsubscriber.sh &
	steam &
	thunderbird &
	kitty --class startupterm1 &
	kitty --class startupterm2 &
	sleep 5
	bspc desktop -f Spotify
	sleep 0.25
	spotify &
	sleep 2
	bspc desktop -f 1
	sleep 0.25
	brave &
	sleep 2
	bspc desktop -f 2
	sleep 0.25
	brave &
	sleep 2
	bspc desktop -f 1
    discord &
fi
